### ISSUE TITLE
Add the boycott Airbnb pledge 

### ISSUE THREAD

**Issue by jaycblat** [adasomg/airbnb-is-antisemitic-blacklist#1]
Available here: https://docs.google.com/forms/d/e/1FAIpQLSddMr9pxH3892eu_F0igbiD0SYiKOsHx_3komQ0BYEJ04JVOw/viewform

**Comment by adasomg** [comment]
Done. Thank you!
https://github.com/adasomg/airbnb-is-antisemitic-blacklist/commit/d4e7731c84a9e9c4f33ad599de261f14c277de35
